services:
  - type: web
    name: flowise-backend
    env: docker
    plan: starter
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
  - key: FLOWISE_USERNAME
    value: admin
  - key: FLOWISE_PASSWORD
    value: Anyaforger_290034
  - key: PORT
    value: 3000
  - key: GROQ_API_KEY
    value: ${GROQ_API_KEY}
  - key: FLOWISE_CORS_ORIGIN
    value: https://my-portfolio-sepia-eta-66.vercel.app

