services:
  - type: web
    name: flowise-backend
    env: docker
    plan: starter
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
  - key: FLOWISE_USERNAME
    value: admin
  - key: FLOWISE_PASSWORD
    value: Anyaforger_290034
  - key: PORT
    value: 3000
  - key: GROQ_API_KEY
    value: aec866f5-5a62-44cd-81d4-af532db235af
  - key: CORS_ORIGINS
    value: https://my-portfolio-sepia-eta-66.vercel.app

